USE [DataFromSIR]

GO

SET ANSI_PADDING ON


GO

CREATE NONCLUSTERED INDEX [ix-code-date-nhs] ON [dbo].[journal]
(
	[readcode] ASC,
	[entrydate] ASC,
	[NHSNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO


